/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MathTestInterface extends utils.Interface {
  functions: {
    "expV1(int256)": FunctionFragment;
    "expV2(int256)": FunctionFragment;
    "lnV1(int256)": FunctionFragment;
    "lnV2(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "expV1", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "expV2", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "lnV1", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "lnV2", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "expV1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expV2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lnV1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lnV2", data: BytesLike): Result;

  events: {};
}

export interface MathTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MathTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    expV1(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    "expV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    expV2(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    "expV2(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    lnV1(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    "lnV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    lnV2(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;

    "lnV2(uint256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { r: BigNumber }>;
  };

  expV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "expV1(int256)"(
    x: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  expV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "expV2(int256)"(
    x: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lnV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "lnV1(int256)"(
    x: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lnV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "lnV2(uint256)"(
    x: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    expV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "expV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "expV2(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lnV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "lnV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lnV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "lnV2(uint256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    expV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "expV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "expV2(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lnV1(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "lnV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lnV2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "lnV2(uint256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    expV1(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "expV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expV2(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "expV2(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lnV1(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lnV1(int256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lnV2(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lnV2(uint256)"(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
