/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type SwapStruct = {
  swapType: BigNumberish;
  tokenOut: string;
  tokenOutCurrencyKey: BytesLike;
  poolFee: BigNumberish;
};

export type SwapStructOutput = [number, string, string, number] & {
  swapType: number;
  tokenOut: string;
  tokenOutCurrencyKey: string;
  poolFee: number;
};

export interface MultistepSwapperInterface extends utils.Interface {
  functions: {
    "init(address,address)": FunctionFragment;
    "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "init",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [string, BytesLike, BigNumberish, SwapStruct[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;

  events: {};
}

export interface MultistepSwapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MultistepSwapperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    init(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "init(address,address)"(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swap(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)"(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  init(
    _swapRouter: string,
    _synthetix: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "init(address,address)"(
    _swapRouter: string,
    _synthetix: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swap(
    tokenIn: string,
    tokenInCurrencyKey: BytesLike,
    amountIn: BigNumberish,
    swaps: SwapStruct[],
    amountOutMinimum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)"(
    tokenIn: string,
    tokenInCurrencyKey: BytesLike,
    amountIn: BigNumberish,
    swaps: SwapStruct[],
    amountOutMinimum: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    init(
      _swapRouter: string,
      _synthetix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "init(address,address)"(
      _swapRouter: string,
      _synthetix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    swap(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)"(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    init(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "init(address,address)"(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swap(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)"(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    init(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "init(address,address)"(
      _swapRouter: string,
      _synthetix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "swap(address,bytes32,uint256,(uint8,address,bytes32,uint24)[],uint256)"(
      tokenIn: string,
      tokenInCurrencyKey: BytesLike,
      amountIn: BigNumberish,
      swaps: SwapStruct[],
      amountOutMinimum: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
